[package]
name = "day03"
version = "0.1.0"
authors = ["Alex Rice <alexrice999@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day03"
path = "main.rs"
