[package]
name = "day4"
version = "0.1.0"
authors = ["Alex Rice <alexrice999@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"

[[bin]]
name = "day4"
path = "main.rs"
